//github API
export const ADD_TO_CART = 'ADD_TO_CART'
export const FETCHING_BOOK_LIST = 'FETCHING_BOOK_LIST'
export const FETCHING_BOOK_LIST_SUCCESS = 'FETCHING_BOOK_LIST_SUCCESS'
export const FETCHING_BOOK_LIST_FAILURE = 'FETCHING_BOOK_LIST_FAILURE'
